- name: configure db server
  hosts: web
  become: yes
  vars:
    login_host: db.daws78s.xyz
  tasks: 
  - name: install mySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  
  - name: start nd enable MySQL server
    ansible.builtin.server:
      name: mysqld
      state: started
      enabled: started

  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "output: {{mysql_connection_output}}"